name: PlanetScale migrate and deploy
description: PlanetScale migrate and deploy with GitHub Actions
branding:
  icon: database
  color: gray-dark
inputs:
  planetscale-service-token-id:
    description: The PlanetScale service token ID
    required: true
  planetscale-service-token:
    description: The PlanetScale service token value
    required: true
  planetscale-org-name:
    description: The PlanetScale organization name
    required: true
  planetscale-db-name:
    description: The PlanetScale database name
    required: true
  branch-name:
    description: The name of the PlanetScale branch to create
    required: false
  migrate-command:
    description: The command to run database migrations
    required: true
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.planetscale-service-token-id }}
    - ${{ inputs.planetscale-service-token }}
    - ${{ inputs.planetscale-org-name }}
    - ${{ inputs.planetscale-db-name }}
    - ${{ inputs.branch-name }}
    - ${{ inputs.migrate-command }}
