name: PlanetScale migrate and deploy
description: PlanetScale migrate and deploy with GitHub Actions
branding:
  icon: database
  color: gray-dark
inputs:
  planetscale-service-token-id:
    description: The PlanetScale service token ID
    required: true
  planetscale-service-token:
    description: The PlanetScale service token value
    required: true
  planetscale-org-name:
    description: The PlanetScale organization name
    required: true
  planetscale-db-name:
    description: The PlanetScale database name
    required: true
  branch-name:
    description: The name of the PlanetScale branch to create
    required: false
  migrate-command:
    description: The command to run database migrations
    required: true
runs:
  using: composite
  steps:
    - name: Install the latest pscale CLI from GitHub releases
      uses: jaxxstorm/action-install-gh-release@v1.9.0
      with:
        repo: planetscale/cli

    - name: Run the migration script
      env:
        PLANETSCALE_SERVICE_TOKEN_ID: ${{ inputs.planetscale-service-token-id }}
        PLANETSCALE_SERVICE_TOKEN: ${{ inputs.planetscale-service-token }}
      run: |
        ${{ github.action_path }}/script.sh \
          "${{ inputs.planetscale-org-name }}" \
          "${{ inputs.planetscale-db-name }}" \
          "${{ inputs.branch-name }}" \
          "${{ inputs.migrate-command }}"
      shell: bash
